version: "3.8"
services:
  database_zoo:
    image: "postgres:15.2"
    restart: always
    env_file:
      - database.env
    ports:
      - "5436:5432"
    volumes:
      - /var/docker-volumes/postgres-data-zoo:/var/lib/postgresql/data/