version: "3.8"

services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6666:6666"
    environment:
      - PORT=6666
      - DATASOURCE_URL=jdbc:postgresql://database_zoo:5432/instazoo
      - SECURITY_KEY=D9D323C5E55F45C206D7880329B1721A4334C00F336E5F2F1E9DAB745FF44837
      - DB_NAME=admin
      - DB_PASS=admin

    depends_on:
      - database_zoo

  database_zoo:
    container_name: database_zoo
    image: "postgres:15.2"
    restart: always
    env_file:
      - database.env
    ports:
      - "5436:5432"
    volumes:
      - /var/docker-volumes/postgres-data-zoo:/var/lib/postgresql/data/