version: "3.8"
services:
  database:
    image: "postgres:15.2"
    restart: always
    env_file:
      - database.env
    ports:
      - "5435:5432"
    volumes:
      - /var/docker-volumes/postgres-data:/var/lib/postgresql/data/