version: "3.8"

services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6666:6666"
    depends_on:
      - database_zoo

  database_zoo:
    container_name: database_zoo
    image: "postgres:15.2"
    restart: always
    env_file:
      - database.env
    ports:
      - "5432:5432"
    volumes:
      - /var/docker-volumes/postgres-data-zoo:/var/lib/postgresql/data/