server:
  port: 6060
  error:
    include-stacktrace: never

auth:
  secret: "D9D323C5E55F45C206D7880329B1721A4334C00F336E5F2F1E9DAB745FF44837"
  prefix: "Bearer "
  header: "Authorization"
  expiration-time: 600000
  refresh-expiration-time: 18000000
  signin-url: "/api/v1/auth/signin"
  signup-url: "/api/v1/auth/signup"
  refresh-token-url: "/api/v1/auth/refresh-token"

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5436/instazoo
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: false
        hbm2ddl:
          auto: validate
  flyway:
    baseline-on-migrate: true
    locations: db/migration
    enabled: true

logging:
  level:
    org.springframework.security: DEBUG