server:
  port: ${PORT}
  error:
    include-stacktrace: never

auth:
  secret: ${SECURITY_KEY}
  prefix: "Bearer "
  header: "Authorization"
  expiration-time: 600000
  refresh-expiration-time: 18000000
  signin-url: "/api/v1/auth/signin"
  signup-url: "/api/v1/auth/signup"
  refresh-token-url: "/api/v1/auth/refresh-token"

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL}
    username: ${DB_NAME}
    password: ${DB_PASS}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: false
        hbm2ddl:
          auto: validate
  flyway:
    baseline-on-migrate: true
    locations: db/migration
    enabled: true

cors:
  allowed-origins:
    - "http://localhost:4200"

  allowed-methods:
    - GET
    - POST
    - PUT

  allowed-headers:
    - "*"

logging:
  level:
    org.springframework.security: DEBUG