server:
  port: 6666
  error:
    include-stacktrace: never

auth:
  secret: "D9D323C5E55F45C206D7880329B1721A4334C00F336E5F2F1E9DAB745FF44837"
  prefix: "Bearer "
  header: "Authorization"
  expiration-time: 600000

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5436/instazoo
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: false
        hbm2ddl:
          auto: none
  flyway:
    baseline-on-migrate: true
    locations: db/migration
    enabled: false

logging:
  level:
    org.springframework.security: DEBUG