server:
  port: ${PORT}
  error:
    path: /api/v1/error

auth:
  secret: ${SECURITY_KEY}
  prefix: "Bearer "
  header: "Authorization"
  expiration-time: 600000
  refresh-expiration-time: 18000000

spring:
  profiles:
    active: local

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL}
    username: ${DB_NAME}
    password: ${DB_PASS}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: validate
  flyway:
    baseline-on-migrate: true
    locations: db/migration
    enabled: true

logging:
  level:
    org.springframework.security: DEBUG